app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('app/task=<int:task_id>/', views.task, name='detail_task'),
    path('add_task/', views.add_task, name='add_task'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task_name = models.CharField(max_length=50, null=False)
    task_detail = models.CharField(max_length=500, null=False)
    parent_task_id = models.IntegerField(max_length=10, null=True, blank=True)
    cost_time = models.IntegerField(null=True)
    deadline_date = models.DateField(null=True)
    register_date = models.DateTimeField(auto_now_add=True, null=False)
    update_date = models.DateTimeField(auto_now_add=True, null=False)
    is_deleted = models.BooleanField(null=True)

    def __str__(self) -> str:
        """task_nameを返す"""
        return self.task_name

app/forms.py
from django import forms

from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name']

    task_name = forms.CharField(max_length=100)
    task_detail = forms.CharField(max_length=1000)
    parent_task_id = forms.IntegerField(required=False)
    cost_time = forms.IntegerField(required=True)
    deadline_date = forms.DateTimeField(required=True)

app/views.py
from django.shortcuts import render, redirect

from .models import Task
from .forms import TaskForm

# Create your views here.
def index(request):
    return render(request, 'app/index.html')

def dashboard(request):
    tasks = Task.objects.order_by('deadline_date')
    context = {'tasks': tasks}
    return render(request, 'app/dashboard.html', context)

def task(request, task_id):
    task = Task.objects.get(id=task_id)
    task_detail = task.task_detail
    context = {'task': task, 'task_detail': task_detail}
    return render(request, 'app/detail_task.html', context)

def add_task(request):
    if request.method != 'POST':
        form = TaskForm()
    else:
        form = TaskForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:dashboard')
    
    context = {'form': form}
    return render(request, 'app/add_task.html', context)

app/templates/app/add_task.html
{% extends "app/base.html" %}

{% block content %}
  <h1>Add task</h1>

  <form action="{% url 'app:add_task' %}" method="post">
    {%  csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
  </form>


{% endblock content %}

app/templates/app/base.html
<h1>Todo App</h1>
<p>Check your today's Tasks and do it immidiately!</p>
<p>
    <a href="{% url 'app:index' %}">Index</a>
    <a href="{% url 'app:dashboard' %}">Dashboard</a>
</p>

{% block content %}{% endblock content %}

app/templates/app/dashboard.html
{% extends "app/base.html" %}

{% block content %}
<h1>Dashboard</h1>
<p>Tasks</p>
<ul>
    {% for task in tasks %}
      <li>
        <a href="{% url 'app:detail_task' task.id %}">{{ task }}</a>
      </li>
    {% empty %}
      <li>no task right now. Add some!</li>
    {% endfor %}
</ul>

<a href="{% url 'app:add_task' %}">Add Task</a>

{% endblock content %}

app/templates/app/detail_task.html
{% extends "app/base.html" %}

{% block content %}
<h1>Task details</h1>
<p>ここがタスク{{ task }}のページ</p>

{% endblock content %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}

<p>ここがindexページ</p>

{% endblock content %}